### PR TITLE
fix: enables chameleon to work with JDK9+

### LINKED ISSUE #90: Support JDK9+
`arquillian-container-chameleon` does not work on JDK9+ due to a failure locating `java.sql.Date` from snakeyaml. This issue was first reported 2 years ago at http://lists.jboss.org/pipermail/wildfly-dev/2016-July/005249.html . It can also be observed by building the source code with OpenJDK 10.

To get arquillian-container-chameleon build on OpenJDK 10 I had to upgrade the `jboss-parent` to 26. To fix the classloader issue, apply the following patch:

```
--- a/arquillian-chameleon-extension/src/main/java/org/arquillian/container/chameleon/ContainerLoader.java
+++ b/arquillian-chameleon-extension/src/main/java/org/arquillian/container/chameleon/ContainerLoader.java
@@ -35,7 +35,7 @@ public class ContainerLoader extends Loader {
 
         File[] archives = Resolver.resolve(cacheFolder, mavenDependencies);
 
-        ClassLoader classloader = new URLClassLoader(Utils.toURLs(archives), null);
+        ClassLoader classloader = new URLClassLoader(Utils.toURLs(archives), ClassLoader.getPlatformClassLoader());
         return loadContainers(classloader, containers);
     }
 }
```

A complicating factor is that many of the containers currently supported do not run on JDK9+ (such as WildFly 9).

### PR DESCRIPTION
**Pull request by bartoszmajsak**
Fixes #90 #138

### CODE REVIEW

File: arquillian-chameleon-runner/runner/src/main/java/org/arquillian/container/chameleon/runner/ArquillianChameleon.java [hunk 1]
```diff
@@ -66,9 +65,9 @@ private boolean isInClientSide(ClassLoader parent) {
     }
 
     private void addsArquillianFile(Path file, ClassLoader classLoader) throws Exception {
-        Method method = URLClassLoader.class.getDeclaredMethod("addURL", new Class[] {URL.class});
-        method.setAccessible(true);
-        method.invoke(classLoader, new Object[] {file.toUri().toURL()});
+        final URL url = file.toUri().toURL();
+        final ClassLoader wrappedClassLoader = URLClassLoader.newInstance(new URL[]{url}, classLoader);
+        Thread.currentThread().setContextClassLoader(wrappedClassLoader);
```
Comment (bartoszmajsak) [inline arquillian-chameleon-runner/runner/src/main/java/org/arquillian/container/chameleon/runner/ArquillianChameleon.java]: @lordofthejars this particular change unblocks Chameleon on JDK9+, as starting from this release system classloader is not anymore a subclass of `URLClassLoader`. That was leading to runtime errors while trying to do that reflective call.

Comment (bartoszmajsak) [reply arquillian-chameleon-runner/runner/src/main/java/org/arquillian/container/chameleon/runner/ArquillianChameleon.java]: A bit more of the technical details can be found here https://community.oracle.com/thread/4011800
